export const COIN_GECKO_TOKEN_MAP = {
    AURORA: 'aurora-near',
    REF: 'ref-finance',
    USDT: 'tether',
    SOL: 'solana',
    ETH: 'ethereum',
    wETH: 'ethereum',
    BTC: 'bitcoin',
    FTT: 'ftx-token',
    MNGO: 'mango-markets',
    AVAX: 'avalanche-2',
    RAY: 'raydium',
    BNB: 'binancecoin',
    GMT: 'stepn',
    SRM: 'serum',
    MSOL: 'msol',
    ADA: 'cardano',
    NEAR: 'near',
    USDC: 'usd-coin',
    stSOL: 'lido-staked-sol',
};
