import { PublicKey } from '@solana/web3.js';
import {MangoPerpMarketConfig, MangoSpotMarketConfig} from "../../type";

export const MANGO_PROGRAM_ID = new PublicKey('mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68');
export const MANGO_REIMBURSEMENT_PROGRAM_ID = new PublicKey('m3roABq4Ta3sGyFRLdY4LH1KN16zBtg586gJ3UxoBzb');
export const MANGO_REIMBURSEMENT_GROUP_KEY = new PublicKey('Hy4ZsZkVa1ZTVa2ghkKY3TsThYEK9MgaL8VPF569jsHP');
export const MANGO_GROUP_KEY = new PublicKey('98pjRuQjK3qA6gXts96PqZT4Ze5QmnCmt3QYjhbUSPue');

export const MANGO_PERP_MARKETS: MangoPerpMarketConfig[] = [
    {
        name: 'MNGO-PERP',
        publicKey: new PublicKey('4nfmQP3KmUqEJ6qJLsS3offKgE96YUB4Rp7UQvm2Fbi9'),
        orderPriceDecimals: 4,
        orderQuantityDecimals: 0,
        leverage: 4,
        marketIndex: 0,
        baseSymbol: 'MNGO',
        baseDecimals: 6,
        quoteDecimals: 6,
        bidsKey: new PublicKey('4XU8wH9ivp7x7ohhTbWUZabg5WVkF7sBtqQCmFEV6qiN'),
        asksKey: new PublicKey('4ZkS7ZZkxfsC3GtvvsHP3DFcUeByU9zzZELS4r8HCELo'),
        eventQueueKey: new PublicKey('7orixrhZpjvofZGWZyyLFxSEt2tfFiost5kHEzd7jdet'),
        mngoVault: new PublicKey('ChtvWUf5qPQaNi8kcwFXLWb6BTrLsADPVMHmqtgQVNvh'),
    },
    {
        name: 'BTC-PERP',
        publicKey: new PublicKey('DtEcjPLyD4YtTBB4q8xwFZ9q49W89xZCZtJyrGebi5t8'),
        orderPriceDecimals: 1,
        orderQuantityDecimals: 4,
        leverage: 20,
        marketIndex: 1,
        baseSymbol: 'BTC',
        baseDecimals: 6,
        quoteDecimals: 6,
        bidsKey: new PublicKey('Bc8XaK5UTuDSCBtiESSUxBSb9t6xczhbAJnesPamMRir'),
        asksKey: new PublicKey('BkWRiarqxP5Gwx7115LQPbjRmr3NjuSRXWBnduXXLGWR'),
        eventQueueKey: new PublicKey('7t5Me8RieYKsFpfLEV8jnpqcqswNpyWD95ZqgUXuLV8Z'),
        mngoVault: new PublicKey('CF8sDcPztLDkvnEbYnCaXiDxhUpZ2uKLStpmFfRDNxSd'),
    },
    {
        name: 'ETH-PERP',
        publicKey: new PublicKey('DVXWg6mfwFvHQbGyaHke4h3LE9pSkgbooDSDgA4JBC8d'),
        orderPriceDecimals: 1,
        orderQuantityDecimals: 3,
        leverage: 20,
        marketIndex: 2,
        baseSymbol: 'ETH',
        baseDecimals: 6,
        quoteDecimals: 6,
        bidsKey: new PublicKey('DQv2sWhaHYbKrobHH6jAdkAXw13mnDdM9hVfRQtrUcMe'),
        asksKey: new PublicKey('8NhLMV6huneGAqijuUgUFSshbAfXxdNj6ZMHSLb9aW8K'),
        eventQueueKey: new PublicKey('9vDfKNPJkCvQv9bzR4JNTGciQC2RVHPVNMMHiVDgT1mw'),
        mngoVault: new PublicKey('DMNtyjf5jUWzK3qCGrMBeRSmYQ43agD1eXScSqxZ67gT'),
    },
    {
        name: 'SOL-PERP',
        publicKey: new PublicKey('2TgaaVoHgnSeEtXvWTx13zQeTf4hYWAMEiMQdcG6EwHi'),
        orderPriceDecimals: 2,
        orderQuantityDecimals: 2,
        leverage: 20,
        marketIndex: 3,
        baseSymbol: 'SOL',
        baseDecimals: 9,
        quoteDecimals: 6,
        bidsKey: new PublicKey('Fu8q5EiFunGwSRrjFKjRUoMABj5yCoMEPccMbUiAT6PD'),
        asksKey: new PublicKey('9qUxMSWBGAeNmXusQHuLfgSuYJqADyYoNLwZ63JJSi6V'),
        eventQueueKey: new PublicKey('31cKs646dt1YkA3zPyxZ7rUAkxTBz279w4XEobFXcAKP'),
        mngoVault: new PublicKey('HzHhbkEvjU4X65CK2xBBxmmJ79tLRDk2X5WfkaH1FbMq'),
    },
    {
        name: 'SRM-PERP',
        publicKey: new PublicKey('4GkJj2znAr2pE2PBbak66E12zjCs2jkmeafiJwDVM9Au'),
        orderPriceDecimals: 3,
        orderQuantityDecimals: 1,
        leverage: 8,
        marketIndex: 5,
        baseSymbol: 'SRM',
        baseDecimals: 6,
        quoteDecimals: 6,
        bidsKey: new PublicKey('E8Dv9giJQgPqNaBxF9WKDUhJD7GZ5fwXfF1NQfeCCaQp'),
        asksKey: new PublicKey('GMv773oHiNd4jaj8uQvr1kbzroY5BDK7QTNHD14ATjGJ'),
        eventQueueKey: new PublicKey('BXSPmdHWP6fMqsCsT6kG8UN9uugAJxdDkQWy87njUQnL'),
        mngoVault: new PublicKey('9dTZh76cAbp287bbG91uHU3mmWNoDdSthSuWkYmtVGNJ'),
    },
    {
        name: 'RAY-PERP',
        publicKey: new PublicKey('6WGoQr5mJAEpYCdX6qjju2vEnJuD7e8ZeYes7X7Shi7E'),
        orderPriceDecimals: 3,
        orderQuantityDecimals: 1,
        leverage: 8,
        marketIndex: 6,
        baseSymbol: 'RAY',
        baseDecimals: 6,
        quoteDecimals: 6,
        bidsKey: new PublicKey('9AHm1nsxG1e3zkHnFLzYUXd17qnCgM7aFJDDApXXrhVU'),
        asksKey: new PublicKey('43dVtcFTgDHHr32V6vhvxU2gg11wK7oyK8DdfTQ2pQsy'),
        eventQueueKey: new PublicKey('Css2MQhEvXMTKjp9REVZR9ZyUAYAZAPrnDvRoPxrQkeN'),
        mngoVault: new PublicKey('3jbET1DX1AM8E3FVU9kijmdfPENeEVBMHn7bhsxkugNs'),
    },
    {
        name: 'FTT-PERP',
        publicKey: new PublicKey('AhgEayEGNw46ALHuC5ASsKyfsJzAm5JY8DWqpGMQhcGC'),
        orderPriceDecimals: 3,
        orderQuantityDecimals: 1,
        leverage: 10,
        marketIndex: 8,
        baseSymbol: 'FTT',
        baseDecimals: 6,
        quoteDecimals: 6,
        bidsKey: new PublicKey('5xihpD8yz9vt95WSHVpW8pVykffW7h5VHb2LkhGBMUck'),
        asksKey: new PublicKey('G9HtAEwHRYBrz9ZpdDJH8Qs1hEZqNJ1BPm3veBsmEXbX'),
        eventQueueKey: new PublicKey('5pHAhyEphQRVvLqvYF7dziofR52yZWuq8DThQFJvJ7r5'),
        mngoVault: new PublicKey('HtKPzDC2TcMwCkHNMs2M4ZRWoooufshBfE4HGPJwbrZ6'),
    },
    {
        name: 'ADA-PERP',
        publicKey: new PublicKey('Bh9UENAncoTEwE7NDim8CdeM1GPvw6xAT4Sih2rKVmWB'),
        orderPriceDecimals: 4,
        orderQuantityDecimals: 0,
        leverage: 10,
        marketIndex: 9,
        baseSymbol: 'ADA',
        baseDecimals: 6,
        quoteDecimals: 6,
        bidsKey: new PublicKey('ivYhvYgribqdCzDg4m8fUF9ejgJHE4mnRUseR4d9khN'),
        asksKey: new PublicKey('F4UTmEXxEUgGSL7P3HePAuz3PsXvx6hWr256vqVnzxKE'),
        eventQueueKey: new PublicKey('G6Dsw9KnP4G38hePtedTH6gDfDQmPJGJw8zipBJvKc12'),
        mngoVault: new PublicKey('EX5YRv7BpEcQL5SxNx37iugzj7V5nHqSZWccKRhSFa9N'),
    },
    {
        name: 'BNB-PERP',
        publicKey: new PublicKey('CqxX2QupYiYafBSbA519j4vRVxxecidbh2zwX66Lmqem'),
        orderPriceDecimals: 1,
        orderQuantityDecimals: 3,
        leverage: 10,
        marketIndex: 11,
        baseSymbol: 'BNB',
        baseDecimals: 8,
        quoteDecimals: 6,
        bidsKey: new PublicKey('6Pg82x4SSejLny5v1wSWs7QhnheLDq7EX1pMVY8LTsB3'),
        asksKey: new PublicKey('6n2ooaNFP6X54ZiwDskhhVeW81F4hHNEibsJ8vfjVNDU'),
        eventQueueKey: new PublicKey('GmX4qXMpXvs1DuUXNB4eqL1rfF8LeYEjkKgpFeYsm55n'),
        mngoVault: new PublicKey('6DuaYV1uAWSh6CcpyY1cYihyXRn13pL7xR4HFwXxrHER'),
    },
    {
        name: 'AVAX-PERP',
        publicKey: new PublicKey('EAC7jtzsoQwCbXj1M3DapWrNLnc3MBwXAarvWDPr2ZV9'),
        orderPriceDecimals: 2,
        orderQuantityDecimals: 2,
        leverage: 10,
        marketIndex: 12,
        baseSymbol: 'AVAX',
        baseDecimals: 8,
        quoteDecimals: 6,
        bidsKey: new PublicKey('BD1vpQjLXx7Rmd5n1SFNTLcwujPYTnFpoaArvPd9ixB9'),
        asksKey: new PublicKey('8Q11iGHXFTr267J4bgbeEeWPYPSANVcs6NQWHQK4UrNs'),
        eventQueueKey: new PublicKey('5Grgo9kLu692SUcJ6S7jtbi1WkdwiyRWgThAfN1PcvbL'),
        mngoVault: new PublicKey('HaGVpy6RbgkoofTdMxkSN5o2imraPvwk9rH7WhoahHft'),
    },
    {
        name: 'GMT-PERP',
        publicKey: new PublicKey('3hBYgfMHogR8X2JkpxvT8HMtUSbrE2PE61q64gZkWArr'),
        orderPriceDecimals: 4,
        orderQuantityDecimals: 0,
        leverage: 8,
        marketIndex: 14,
        baseSymbol: 'GMT',
        baseDecimals: 9,
        quoteDecimals: 6,
        bidsKey: new PublicKey('67jnTtxDdDqz6R18Do3AUUjBbZT3yysprGLhaucyKd93'),
        asksKey: new PublicKey('DstVrGA3CBcq1r7op4yU7dX3sirzSgz1uicn63aYBMGz'),
        eventQueueKey: new PublicKey('J2WYiw67VeGkPvmM3fi65H9KxDgCf79fNwspcD3ycubK'),
        mngoVault: new PublicKey('4qh34T1MZV8aTd9DGKteojRJBRotqvhLytuE6xZDXf8N'),
    },
];

export const MANGO_SPOT_MARKETS: MangoSpotMarketConfig[] = [
    {
        name: 'MNGO/USDC',
        publicKey: new PublicKey('3d4rzwpy9iGdCZvgxcu7B1YocYffVLsQXPXkBZKt2zLc'),
        orderPriceDecimals: 4,
        orderQuantityDecimals: 0,
        leverage: 1.25,
        marketIndex: 0,
        baseSymbol: 'MNGO',
        baseDecimals: 6,
        quoteDecimals: 6,
        baseLotSize: 1000000,
        quoteLotSize: 100,
        bidsKey: new PublicKey('3nAdH9wTEhPoW4e2s8K2cXfn4jZH8FBCkUqtzWpsZaGb'),
        asksKey: new PublicKey('HxbWm3iabHEFeHG9LVGYycTwn7aJVYYHbpQyhZhAYnfn'),
        eventQueueKey: new PublicKey('H1VVmwbM96BiBJq46zubSBm6VBhfM2FUhLVUqKGh1ee9'),
        requestQueueKey: new PublicKey('EgafUKwVAmEj2czrt7HkWnZJLZSAK9BDN5aGQpLypAys'),
        baseVaultKey: new PublicKey('7Ex7id4G37HynuiCAv5hTYM4BnPB9y4NU85QcaNWZy3G'),
        quoteVaultKey: new PublicKey('9UB1NhGeDuV1apHdtK5LeAEjP7kZFH8vVYGdh2yGFRi8'),
        vaultSignerKey: new PublicKey('BFkxdUwW17eANhfs1xNmBqEcegb4EStQxVb5VaMS2dq6'),
    },
    {
        name: 'BTC/USDC',
        publicKey: new PublicKey('A8YFbxQYFVqKZaoYJLLUVcQiWP7G2MeEgW5wsAQgMvFw'),
        orderPriceDecimals: 1,
        orderQuantityDecimals: 4,
        leverage: 5,
        marketIndex: 1,
        baseSymbol: 'BTC',
        baseDecimals: 6,
        quoteDecimals: 6,
        baseLotSize: 100,
        quoteLotSize: 10,
        bidsKey: new PublicKey('6wLt7CX1zZdFpa6uGJJpZfzWvG6W9rxXjquJDYiFwf9K'),
        asksKey: new PublicKey('6EyVXMMA58Nf6MScqeLpw1jS12RCpry23u9VMfy8b65Y'),
        eventQueueKey: new PublicKey('6NQqaa48SnBBJZt9HyVPngcZFW81JfDv9EjRX2M4WkbP'),
        requestQueueKey: new PublicKey('H6UaUrNVELJgTqao1CNL4252kShLKSfwoboT8tF7HNtB'),
        baseVaultKey: new PublicKey('GZ1YSupuUq9kB28kX9t1j9qCpN67AMMwn4Q72BzeSpfR'),
        quoteVaultKey: new PublicKey('7sP9fug8rqZFLbXoEj8DETF81KasaRA1fr6jQb6ScKc5'),
        vaultSignerKey: new PublicKey('GBWgHXLf1fX4J1p5fAkQoEbnjpgjxUtr4mrVgtj9wW8a'),
    },
    {
        name: 'ETH/USDC',
        publicKey: new PublicKey('4tSvZvnbyzHXLMTiFonMyxZoHmFqau1XArcRCVHLZ5gX'),
        orderPriceDecimals: 2,
        orderQuantityDecimals: 3,
        leverage: 5,
        marketIndex: 2,
        baseSymbol: 'ETH',
        baseDecimals: 6,
        quoteDecimals: 6,
        baseLotSize: 1000,
        quoteLotSize: 10,
        bidsKey: new PublicKey('8tFaNpFPWJ8i7inhKSfAcSestudiFqJ2wHyvtTfsBZZU'),
        asksKey: new PublicKey('2po4TC8qiTgPsqcnbf6uMZRMVnPBzVwqqYfHP15QqREU'),
        eventQueueKey: new PublicKey('Eac7hqpaZxiBtG4MdyKpsgzcoVN6eMe9tAbsdZRYH4us'),
        requestQueueKey: new PublicKey('6yJsfduT4Av6xaECAoXf4cXHaQQYjf78D1FG3WDyuxdr'),
        baseVaultKey: new PublicKey('7Nw66LmJB6YzHsgEGQ8oDSSsJ4YzUkEVAvysQuQw7tC4'),
        quoteVaultKey: new PublicKey('EsDTx47jjFACkBhy48Go2W7AQPk4UxtT4765f3tpK21a'),
        vaultSignerKey: new PublicKey('C5v68qSzDdGeRcs556YoEMJNsp8JiYEiEhw2hVUR8Z8y'),
    },
    {
        name: 'SOL/USDC',
        publicKey: new PublicKey('9wFFyRfZBsuAha4YcuxcXLKwMxJR43S7fPfQLusDBzvT'),
        orderPriceDecimals: 3,
        orderQuantityDecimals: 1,
        leverage: 5,
        marketIndex: 3,
        baseSymbol: 'SOL',
        baseDecimals: 9,
        quoteDecimals: 6,
        baseLotSize: 100000000,
        quoteLotSize: 100,
        bidsKey: new PublicKey('14ivtgssEBoBjuZJtSAPKYgpUK7DmnSwuPMqJoVTSgKJ'),
        asksKey: new PublicKey('CEQdAFKdycHugujQg9k2wbmxjcpdYZyVLfV9WerTnafJ'),
        eventQueueKey: new PublicKey('5KKsLVU6TcbVDK4BS6K1DGDxnh4Q9xjYJ8XaDCG5t8ht'),
        requestQueueKey: new PublicKey('AZG3tFCFtiCqEwyardENBQNpHqxgzbMw8uKeZEw2nRG5'),
        baseVaultKey: new PublicKey('36c6YqAwyGKQG66XEp2dJc5JqjaBNv7sVghEtJv4c7u6'),
        quoteVaultKey: new PublicKey('8CFo8bL8mZQK8abbFyypFMwEDd8tVJjHTTojMLgQTUSZ'),
        vaultSignerKey: new PublicKey('F8Vyqk3unwxkXukZFQeYyGmFfTG3CAX4v24iyrjEYBJV'),
    },
    {
        name: 'SRM/USDC',
        publicKey: new PublicKey('ByRys5tuUWDgL73G8JBAEfkdFf8JWBzPBDHsBVQ5vbQA'),
        orderPriceDecimals: 3,
        orderQuantityDecimals: 1,
        leverage: 5,
        marketIndex: 5,
        baseSymbol: 'SRM',
        baseDecimals: 6,
        quoteDecimals: 6,
        baseLotSize: 100000,
        quoteLotSize: 100,
        bidsKey: new PublicKey('AuL9JzRJ55MdqzubK4EutJgAumtkuFcRVuPUvTX39pN8'),
        asksKey: new PublicKey('8Lx9U9wdE3afdqih1mCAXy3unJDfzSaXFqAvoLMjhwoD'),
        eventQueueKey: new PublicKey('6o44a9xdzKKDNY7Ff2Qb129mktWbsCT4vKJcg2uk41uy'),
        requestQueueKey: new PublicKey('Hr8Z93aWe4hhJbC5i7YTsPaSToziVh3vyMfv9GRqKFCh'),
        baseVaultKey: new PublicKey('Ecfy8et9Mft9Dkavnuh4mzHMa2KWYUbBTA5oDZNoWu84'),
        quoteVaultKey: new PublicKey('hUgoKy5wjeFbZrXDW4ecr42T4F5Z1Tos31g68s5EHbP'),
        vaultSignerKey: new PublicKey('GVV4ZT9pccwy9d17STafFDuiSqFbXuRTdvKQ1zJX6ttX'),
    },
    {
        name: 'RAY/USDC',
        publicKey: new PublicKey('2xiv8A5xrJ7RnGdxXB42uFEkYHJjszEhaJyKKt4WaLep'),
        orderPriceDecimals: 4,
        orderQuantityDecimals: 1,
        leverage: 5,
        marketIndex: 6,
        baseSymbol: 'RAY',
        baseDecimals: 6,
        quoteDecimals: 6,
        baseLotSize: 100000,
        quoteLotSize: 100,
        bidsKey: new PublicKey('Hf84mYadE1VqSvVWAvCWc9wqLXak4RwXiPb4A91EAUn5'),
        asksKey: new PublicKey('DC1HsWWRCXVg3wk2NndS5LTbce3axwUwUZH1RgnV4oDN'),
        eventQueueKey: new PublicKey('H9dZt8kvz1Fe5FyRisb77KcYTaN8LEbuVAfJSnAaEABz'),
        requestQueueKey: new PublicKey('39mE6bYktM1XAKKmB6WN971X3Sa1yGkHxtCTWMkVrwN2'),
        baseVaultKey: new PublicKey('GGcdamvNDYFhAXr93DWyJ8QmwawUHLCyRqWL3KngtLRa'),
        quoteVaultKey: new PublicKey('22jHt5WmosAykp3LPGSAKgY45p7VGh4DFWSwp21SWBVe'),
        vaultSignerKey: new PublicKey('FmhXe9uG6zun49p222xt3nG1rBAkWvzVz7dxERQ6ouGw'),
    },
    {
        name: 'FTT/USDC',
        publicKey: new PublicKey('2Pbh1CvRVku1TgewMfycemghf6sU9EyuFDcNXqvRmSxc'),
        orderPriceDecimals: 3,
        orderQuantityDecimals: 1,
        leverage: 5,
        marketIndex: 8,
        baseSymbol: 'FTT',
        baseDecimals: 6,
        quoteDecimals: 6,
        baseLotSize: 100000,
        quoteLotSize: 100,
        bidsKey: new PublicKey('9HTDV2r7cQBUKL3fgcJZCUfmJsKA9qCP7nZAXyoyaQou'),
        asksKey: new PublicKey('EpnUJCMCQNZi45nCBoNs6Bugy67Kj3bCSTLYPfz6jkYH'),
        eventQueueKey: new PublicKey('2XHxua6ZaPKpCGUNvSvTwc9teJBmexp8iMWCLu4mtzGb'),
        requestQueueKey: new PublicKey('2ncWnY9QuCdNAX4gLutkNoKr9R1owDY1bhLLV1yH8Ukf'),
        baseVaultKey: new PublicKey('4LXjM6rptNvhBZTcWk4AL49oF4oA8AH7D4CV6z7tmpX3'),
        quoteVaultKey: new PublicKey('2ycZAqQ3YNPfBZnKTbz2FqPiV7fmTQpzF95vjMUekP5z'),
        vaultSignerKey: new PublicKey('B5b9ddFHrjndUieLAKkyzB1xmq8sNqGGZPmbyYWPzCyu'),
    },
    {
        name: 'MSOL/USDC',
        publicKey: new PublicKey('6oGsL2puUgySccKzn9XA9afqF217LfxP5ocq4B3LWsjy'),
        orderPriceDecimals: 3,
        orderQuantityDecimals: 3,
        leverage: 5,
        marketIndex: 10,
        baseSymbol: 'MSOL',
        baseDecimals: 9,
        quoteDecimals: 6,
        baseLotSize: 1000000,
        quoteLotSize: 1,
        bidsKey: new PublicKey('8qyWhEcpuvEsdCmY1kvEnkTfgGeWHmi73Mta5jgWDTuT'),
        asksKey: new PublicKey('PPnJy6No31U45SVSjWTr45R8Q73X6bNHfxdFqr2vMq3'),
        eventQueueKey: new PublicKey('BC8Tdzz7rwvuYkJWKnPnyguva27PQP5DTxosHVQrEzg9'),
        requestQueueKey: new PublicKey('EHUoDPVVKR5Udp4EZPb4bsHZte5EEHc1PPTPXBgJEPEK'),
        baseVaultKey: new PublicKey('2y3BtF5oRBpLwdoaGjLkfmT3FY3YbZCKPbA9zvvx8Pz7'),
        quoteVaultKey: new PublicKey('6w5hF2hceQRZbaxjPJutiWSPAFWDkp3YbY2Aq3RpCSKe'),
        vaultSignerKey: new PublicKey('9dEVMESKXcMQNndoPc5ji9iTeDJ9GfToboy8prkZeT96'),
    },
    {
        name: 'BNB/USDC',
        publicKey: new PublicKey('4UPUurKveNEJgBqJzqHPyi8DhedvpYsMXi7d43CjAg2f'),
        orderPriceDecimals: 1,
        orderQuantityDecimals: 3,
        leverage: 5,
        marketIndex: 11,
        baseSymbol: 'BNB',
        baseDecimals: 8,
        quoteDecimals: 6,
        baseLotSize: 100000,
        quoteLotSize: 100,
        bidsKey: new PublicKey('XHJx6VrtEjpHhTQVt7KSapsTf63BqrStuFd3X3LSovP'),
        asksKey: new PublicKey('4wZkXYKNcnkkf2ALX3ktRDCuj8Sj1dd2L4APxcKDpgwG'),
        eventQueueKey: new PublicKey('DK7Jw2fZCbTVDF191eXywDFymmbXqGUp4VuERiX6RAR4'),
        requestQueueKey: new PublicKey('DzYpcbvi32Me2KTRnpa18VxDU1VP57nHHS7Ks2wEs9KL'),
        baseVaultKey: new PublicKey('7SjACG2xPdt9ur1Shdav6SwBnr58wRZPxLegJX3e2vhT'),
        quoteVaultKey: new PublicKey('HrxG4K4xSpRfPxSGtMQnnbKRo3r6F2Qj1eyDZXFvP7pe'),
        vaultSignerKey: new PublicKey('xns66Y3kLdMA7aVZciP5pdc46oBD9QHjUrnfTVF3PWp'),
    },
    {
        name: 'AVAX/USDC',
        publicKey: new PublicKey('E8JQstcwjuqN5kdMyUJLNuaectymnhffkvfg1j286UCr'),
        orderPriceDecimals: 2,
        orderQuantityDecimals: 2,
        leverage: 5,
        marketIndex: 12,
        baseSymbol: 'AVAX',
        baseDecimals: 8,
        quoteDecimals: 6,
        baseLotSize: 1000000,
        quoteLotSize: 100,
        bidsKey: new PublicKey('925NuYb44V63wNRooM5tBFNCXM5daD72m6KDxoCmYpYX'),
        asksKey: new PublicKey('q2eUYuqJeBD6DndxDQ2tEuFqAe6j9j9jMtMnkkKU5P9'),
        eventQueueKey: new PublicKey('HY7ZpmQ6VXLHKxN4cruFKMTNu42EbjPEDthyGPnsYYHq'),
        requestQueueKey: new PublicKey('HvxcJ8Nbd6HcoN1ud7eA4JXvASxLERSob1HSNM5frYhW'),
        baseVaultKey: new PublicKey('GCy2YwPXnK8XSaTzekBXqk7QM39obxA4uASsC316KpZ5'),
        quoteVaultKey: new PublicKey('8PDzWsq8J4AWBk1YSnS5NHSpZWhXxaM5dvGQLxgWxAX6'),
        vaultSignerKey: new PublicKey('CUG8UvhW1q6ojQC2gyga8x67nde37vvsJUUbinTaPU9N'),
    },
    {
        name: 'GMT/USDC',
        publicKey: new PublicKey('9KLmeRBpT4chsxkJatfDdzrtTBvBastYp9wMe712ASCg'),
        orderPriceDecimals: 3,
        orderQuantityDecimals: 2,
        leverage: 2,
        marketIndex: 14,
        baseSymbol: 'GMT',
        baseDecimals: 9,
        quoteDecimals: 6,
        baseLotSize: 10000000,
        quoteLotSize: 10,
        bidsKey: new PublicKey('EzVutiMEE8gyeyaiQ4jUrSn4LXwrDmRkuNK4wcRctJxW'),
        asksKey: new PublicKey('Eg2PKQ3BHWsRCMLZQaJrAXMCEWoEsNXPY8BLLk5AHsrM'),
        eventQueueKey: new PublicKey('92AfWEUqA2RQjD46otvaXEA3CQ4qBFi2K8AmCBwwghHG'),
        requestQueueKey: new PublicKey('DtQRDbouSPoqgqKTKrEdSvnYMxp1nxheFS445r3qrkYn'),
        baseVaultKey: new PublicKey('2oxTZXWtZQiZ4amFfhFHJSPoXGhi4gtBV8SF9BZTF4kg'),
        quoteVaultKey: new PublicKey('m6jKUb5KmKtEDMAP8FpENv3k2ecRWDxvM1azgcQbVcw'),
        vaultSignerKey: new PublicKey('26hKhwGrpPabhMS4F2s7LixnycMZhJEcegBvxr7n4LbY'),
    },
];
