import { PublicKey } from '@solana/web3.js';
import { SerumMarketConfig } from '../../type';

export const SERUM_PROGRAM_ID = new PublicKey('srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX');

export const SERUM_MARKETS: SerumMarketConfig[] = [
    {
        name: 'SOL/USDC',
        address: new PublicKey('8BnEgHoWFysVcuFFX7QztDmzuH8r5ZFvyP3sYwn1XTh6'),
        baseSymbol: 'SOL',
        quoteSymbol: 'USDC',
        orderPriceDecimals: 3,
        orderQuantityDecimals: 3,
        leverage: 1,
        baseLotSize: 1000000,
        quoteLotSize: 1,
        bids: new PublicKey('5jWUncPNBMZJ3sTHKmMLszypVkoRK6bfEQMQUHweeQnh'),
        asks: new PublicKey('EaXdHx7x3mdGA38j5RSmKYSXMzAFzzUXCLNBEDXDn1d5'),
        requestQueue: new PublicKey('CPjXDcggXckEq9e4QeXUieVJBpUNpLEmpihLpg5vWjGF'),
        eventQueue: new PublicKey('8CvwxZ9Db6XbLD46NZwwmVDZZRDy7eydFcAGkXKh9axa'),
        baseVault: new PublicKey('CKxTHwM9fPMRRvZmFnFoqKNd9pQR21c5Aq9bh5h9oghX'),
        quoteVault: new PublicKey('6A5NHCj1yF6urc9wZNe6Bcjj4LVszQNj5DwAWG97yzMu'),
        vaultSigner: new PublicKey('CTz5UMLQm2SRWHzQnU62Pi4yJqbNGjgRBHqqp6oDHfF7'),
    },
    {
        name: 'wETH/USDC',
        address: new PublicKey('FZxi3yWkE5mMjyaZj6utmYL54QQYfMCKMcLaQZq4UwnA'),
        baseSymbol: 'wETH',
        quoteSymbol: 'USDC',
        orderPriceDecimals: 0,
        orderQuantityDecimals: 4,
        leverage: 1,
        baseLotSize: 10000,
        quoteLotSize: 100,
        bids: new PublicKey('aknvfZ4mKykoGSNy6ZGUjKGz8xKWVKAkqsfHQEvaFJJ'),
        asks: new PublicKey('51QtGepdiruSb1n6pmKHLNaRNT6jpAqquF71G7Ux493Y'),
        requestQueue: new PublicKey('XQrNty6sE3Bx8yo1pbFqjK8Pingfat5viCuF55tE7CN'),
        eventQueue: new PublicKey('4v7Tg2bEEV1WHDgXja7KHfJh5zCcWQmafNbt14pUC3PJ'),
        baseVault: new PublicKey('AW9cs18vGQnNitjHpBRFAJCFomncMGkB3qpzVqcSPZzz'),
        quoteVault: new PublicKey('6N4p6Uo4QsFTXCra8Y8suVqCaNSNhTyvEMVJE9ARd1JK'),
        vaultSigner: new PublicKey('G6bwK22tQZwv6zfQXNehuA4rFJRVNxqZW2dr7MGGSfSN'),
    },
    {
        name: 'MNGO/USDC',
        address: new PublicKey('3NnxQvDcZXputNMxaxsGvqiKpqgPfSYXpNigZNFcknmD'),
        baseSymbol: 'MNGO',
        quoteSymbol: 'USDC',
        orderPriceDecimals: 6,
        orderQuantityDecimals: -1,
        leverage: 1,
        baseLotSize: 10000000,
        quoteLotSize: 10,
        bids: new PublicKey('5xcsJ8wAc37HMMWuboeon8EFQFd5xaeeFF7gYWQecJRh'),
        asks: new PublicKey('FS3RJV17qKEtDjsffnbLujxR1qieBFR1Rvvk3jHxb3Ua'),
        requestQueue: new PublicKey('bHULB9gq5RVErH8Z9gKj6N8ZNLpNdiSGCUGb21QiyE2'),
        eventQueue: new PublicKey('L5qRy8coUoZpKTLN3xRXRNThGhQneg7k1fAMqjcE4cN'),
        baseVault: new PublicKey('6pr2nSMUg7Bet39jztkKJ1WtX1AV27vpzzLbWa4Tdrrc'),
        quoteVault: new PublicKey('4pQHik1oQgYJwNRjyzNgTJcxR7Z3BgHPcmj9Gp3gVZyA'),
        vaultSigner: new PublicKey('2g6tJJE8Dk8aVUWuj5ZYaJeSLCMn4qwGFg2WK8vLA4i1'),
    },
    {
        name: 'MSOL/USDC',
        address: new PublicKey('9Lyhks5bQQxb9EyyX55NtgKQzpM4WK7JCmeaWuQ5MoXD'),
        baseSymbol: 'MSOL',
        quoteSymbol: 'USDC',
        orderPriceDecimals: 3,
        orderQuantityDecimals: 3,
        leverage: 1,
        baseLotSize: 1000000,
        quoteLotSize: 1,
        bids: new PublicKey('kB3BTG6Pz3W7JzKQLHyrAZaFk1LVmeeXRP4ZiCKUaA3'),
        asks: new PublicKey('Gi8KdURhXWvsRvDFHpqy1gNfnnYuTsWexQvDpP9711id'),
        requestQueue: new PublicKey('FNoj9fYY9qvt2Wfo2FQwwLEtxMEjLPvbC41qe7PiKcpn'),
        eventQueue: new PublicKey('CsB4XjwH4uZRjRXEXRBFJ3hi3mb9jujzRCW7NXg7TRtX'),
        baseVault: new PublicKey('9LBLMC54awCpsufBA9jm5mbwQbprNqLkSJxnpU7phXsm'),
        quoteVault: new PublicKey('FxBmYB5gdcDGag6992QkB1beMQajWiEhoRsaDYo3oGjm'),
        vaultSigner: new PublicKey('7BP26tWJq4omUnMyYTJZyDAkStuAShV9ZmGEAnv9yKMB'),
    },
    {
        name: 'RAY/USDC',
        address: new PublicKey('DZjbn4XC8qoHKikZqzmhemykVzmossoayV9ffbsUqxVj'),
        baseSymbol: 'RAY',
        quoteSymbol: 'USDC',
        orderPriceDecimals: 3,
        orderQuantityDecimals: 1,
        leverage: 1,
        baseLotSize: 100000,
        quoteLotSize: 100,
        bids: new PublicKey('CXMRrGEseppLPmzYJsx5vYwTkaDEag4A9LJvgrAeNpF'),
        asks: new PublicKey('27BrDDYtv9NDQCALCNnDqe3BqjYkgiaQwKBbyqCA8p8B'),
        requestQueue: new PublicKey('Beni6ohbhLxyyRR2jmAQyvQszYmmMW7atQ8vP4p1kxA3'),
        eventQueue: new PublicKey('EkKZwBeKWPvhraYERfUNr2fdh1eazrbTrQXYkRZs24XB'),
        baseVault: new PublicKey('7ssdQJxVAEBSigoJovgHcchwcEQFPPtYbyzLHDHEewKM'),
        quoteVault: new PublicKey('EBGFfeQ5dVwW4HxtShVbh8aCh2fKJ1r2qXBoa6teUve6'),
        vaultSigner: new PublicKey('HYfri5vWyYiDziQeprFErUTbrWdUnkfAFnAAGApZjdGv'),
    },
    {
        name: 'stSOL/USDC',
        address: new PublicKey('JCKa72xFYGWBEVJZ7AKZ2ofugWPBfrrouQviaGaohi3R'),
        baseSymbol: 'stSOL',
        quoteSymbol: 'USDC',
        orderPriceDecimals: 3,
        orderQuantityDecimals: 1,
        leverage: 1,
        baseLotSize: 100000000,
        quoteLotSize: 100,
        bids: new PublicKey('GUQP2dWc6e2saQJL1Ep3QSZdTboNfpF8uzCj9th4CRUM'),
        asks: new PublicKey('7JynbAyCjg8Rvia8hizfRSaLhEWnHQxxBKUh5FqjRncY'),
        requestQueue: new PublicKey('E8jc4BZmZivHhPDoYUNvfzrD3fB7W8xNv4R7tgdRNByh'),
        eventQueue: new PublicKey('9ttPB4KHXuwxDD8668WiY1L8jdvYMFvZtwKn5PGNMCHX'),
        baseVault: new PublicKey('6q3zjhjZrC2f8Xd8CLqxQJaeSATQDhKMcDvF8KL3yHB4'),
        quoteVault: new PublicKey('BExFcur6aLQBLhtbngfs37yxvNad3N5u1Kg3pWzSeuNn'),
        vaultSigner: new PublicKey('DYVAKTk5icrGV5ouuMyQT2kCAN8ECP5qx9q7Bwk2Uxbi'),
    },
];
