import { PublicKey } from '@solana/web3.js';
import { ZetaAssetConfig, ZetaFutureMarketConfig, ZetaPerpMarketConfig } from '../../type';

export const ZETA_PROGRAM_ID = new PublicKey('ZETAxsqBRek56DhiGXrn75yj2NHU3aYUnxvHXpkf3aD');
export const ZETA_DEX_PROGRAM_ID = new PublicKey('zDEXqXEG7gAyxb1Kg9mK5fPnUdENCGKzWrM21RMdWRq');
export const ZETA_STATE_ACCOUNT = new PublicKey('8eExPiLp47xbSDYkbuem4qnLUpbLTfZBeFuEJoh6EUr2');
export const ZETA_SERUM_AUTHORITY_KEY = new PublicKey('AVNMK6wiGfppdQNg9WKfMRBXefDPGZFh2f3o1fRbgN8n');
export const ZETA_MINT_AUTHORITY_KEY = new PublicKey('AV1UvTbycnqMe4JqHKGCqhACRd2m79YmtEUJrnCUQ3GT');

export const ZETA_ASSETS_CONFIG: ZetaAssetConfig[] = [
    {
        symbol: 'SOL',
        groupAccount: new PublicKey('CoGhjFdyqzMFr5xVgznuBjULvoFbFtNN4bCdQzRArNK2'),
        oracleAccount: new PublicKey('H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG'),
        vaultAccount: new PublicKey('6esygvEPnAV3JKzMKP4ainLvENM2tFYzZ1bpA1NhfDyK'),
        socializedLossAccount: new PublicKey('GMHLjhEosbS7kFzAL557ss9gMP7QfkTT1kBeeicyYvJV'),
        greeksAccount: new PublicKey('FRTCRjf8T5hFHZ9PKGPhYYVRWMFHKje4KwMAEttnDNBe'),
        perpSyncQueue: new PublicKey('5TcAGTDp5iaSLQwRK8m9r3uDQJKeat3vfwe3XA2vw12J'),
    },
    {
        symbol: 'BTC',
        groupAccount: new PublicKey('5XC7JWvLGGds4tjaawgY8FwMdotUb5rrEUmxcmyp5ZiW'),
        oracleAccount: new PublicKey('GVXRSBjFk6e6J3NbVPXohDJetcTjaeeuykUpbQF8UoMU'),
        vaultAccount: new PublicKey('B8y9zLxFGw588CEyoEPkZgGtye6DRhaxppCG4zmfues2'),
        socializedLossAccount: new PublicKey('EwGA8GAotukgr6dLXjhMPPc5zA9nSngynUHqYMnSpmz4'),
        greeksAccount: new PublicKey('6A7KX1pRLYzhP2WRtvfUNBmZit2qFt43yxjGN8N192Th'),
        perpSyncQueue: new PublicKey('zcJWvVdpW3QXYBWyEpjv4ejVXCEUiD41ugocaig44s4'),
    },
    {
        symbol: 'ETH',
        groupAccount: new PublicKey('HPnqfiRSVvuBjfHN9ah4Kecb6J9et2UTnNgUwtAJdV26'),
        oracleAccount: new PublicKey('JBu1AL4obBcCMqKBBxhpWCNUt136ijcuMZLFvTP7iWdB'),
        vaultAccount: new PublicKey('EWGc1UC22P6EWuquZD8vbo7FgnmNFccLDeiita9nubME'),
        socializedLossAccount: new PublicKey('6gucuqexxEuY1BBmpJjYWnTt3QaUqkkmsGE7ydRtCkJY'),
        greeksAccount: new PublicKey('A4ZbGoDjbUhmvgSSZD5J9yjpVsYGXXjoTYZrkRdecGAS'),
        perpSyncQueue: new PublicKey('Gbe7yJ78AK6rmsjVf7CxEYwK71pVEsSzJ97JxuxMbCQ8'),
    },
];

export const ZETA_FUTURE_MARKETS: ZetaFutureMarketConfig[] = [
    {
        name: 'SOL/USDC',
        address: new PublicKey('37Chq2NiKcTekr3WwnDdrV6edC2hVfxVkpEPhXJx2KWV'),
        leverage: 5,
        baseSymbol: 'SOL',
        quoteSymbol: 'USDC',
        marketIndex: 22,
        expiryIndex: 0,
        orderPriceDecimals: 4,
        orderQuantityDecimals: 3,
        greekNodeKey: new PublicKey('7uWp3Rxd1HGdNWNyFjvBW61StEx5A1u11R91cuq1n9RB'),
        zetaBaseVault: new PublicKey('6igTexTX1SQZWLWocqBZxnyo1PWHmkfT1P5DXfsqWtNo'),
        zetaQuoteVault: new PublicKey('Dkkr4RBdUiNywNk7iMo22ZJn2N64gTXew9LSnon6NrJn'),
        bids: new PublicKey('Hd7J5JqypdqHsx5sL8MzSeZawYMetfcw39BggMKvbLBP'),
        asks: new PublicKey('2Ft6YmhBZJpuZL3fHitHHZFKL7m7AyC9XHDMWUZNrEdU'),
        requestQueue: new PublicKey('4huJFYstGNwUFn6f9coGEz44ie2odRoypawVBeidAKka'),
        eventQueue: new PublicKey('2NKGhYsBmC7yWhcWcFqoVKwWr7eKaNaGbjwyHE7SaRjk'),
        baseVault: new PublicKey('3rRQEJufhTkqj3GEtmhHuFS4deZtPAMQjn8esiwXoKfU'),
        quoteVault: new PublicKey('HthbhY6EqH6PGfNYxn6fUujcHzjBiEcYwHobJ1R7aJ2E'),
        baseMint: new PublicKey('5eKdcMwLmsnmZ3CSNLpsumxoFS6WZKNzW1oQNdxipAAM'),
        quoteMint: new PublicKey('2XRjQTsnHLszFwusQoYmbrKASgYbNG4Z8FsZaUo28HBJ'),
        vaultOwner: new PublicKey('6mDNCysDqXyPBKAqVgsZcMkfYdRUwQZrn8tRZcTewcpX'),
    },
    {
        name: 'SOL/USDC',
        address: new PublicKey('652F3eya36Lk9qLa5gMNGQYT1mEKdcLGkiUbxUztSJAh'),
        leverage: 5,
        baseSymbol: 'SOL',
        quoteSymbol: 'USDC',
        marketIndex: 45,
        expiryIndex: 1,
        orderPriceDecimals: 4,
        orderQuantityDecimals: 3,
        greekNodeKey: new PublicKey('73ccTKqh7wEYGDC6mhmB5UfUvZ25FWgj4rtZBwKC4whV'),
        zetaBaseVault: new PublicKey('9NYyGaNC9MaCVM9FtqvtYWp9F8pRvMFpANAqEXHUvFXu'),
        zetaQuoteVault: new PublicKey('77oY1nj4iEw5YHMdLV2Zx1ce3sjM4wdqadEXSkN739jg'),
        bids: new PublicKey('HiMkjfUv11mqaLVt4PYz8Pb1uvtc3yJmi9DBtEjzuHfo'),
        asks: new PublicKey('CVM9TibcKTMgoLLXvL1o7y3A9LbnKhhQkoQ6Hr25SbL1'),
        requestQueue: new PublicKey('9YnB3ySSoj1c2doCttsbVbGmgS84ebWVoVAHDcDGuUrH'),
        eventQueue: new PublicKey('57XHPRzqNQSsCfoQCXNt9ooU1WDsPrMT4ufqQdPZects'),
        baseVault: new PublicKey('5ukPjGw2zMz2YGw9nFeBu3JeyVfcZK7YEq9NRudUtWhP'),
        quoteVault: new PublicKey('D3r1VND8weCNoFybkc5YHeHWaBTdZasysV12J3G6zrPL'),
        baseMint: new PublicKey('Dgwak255GzjK8L4E3b9zD42ZY7sRKLzMsCfRsKSD4kFv'),
        quoteMint: new PublicKey('3Nabu6eAkuq3i2MRTx88B3qtf3ULUoumCKx45hN7CgQL'),
        vaultOwner: new PublicKey('GbFwmBwKqAqAfywz3syXYTJWgj7qFC4hXbYzKfRS6Exg'),
    },
    {
        name: 'BTC/USDC',
        address: new PublicKey('3ubhzPcuqMRKoCrBSxBL4Nnh492sipqaJXmK8TugWXdJ'),
        leverage: 5,
        baseSymbol: 'BTC',
        quoteSymbol: 'USDC',
        marketIndex: 22,
        expiryIndex: 0,
        orderPriceDecimals: 4,
        orderQuantityDecimals: 3,
        greekNodeKey: new PublicKey('6Zia9aEEBnyfxhVqpWHPnZoSkrTpHgcC9PUrwwLizokX'),
        zetaBaseVault: new PublicKey('JCfQiCrKD8puLpmzxqxdQRULjGNr9uYpS4KqPtrj8Knc'),
        zetaQuoteVault: new PublicKey('6W6WM1hFCoA3SBTCd2FiF4zLC7DVDpfoFCscQjVwYK1X'),
        bids: new PublicKey('WXzAVceEYY4ugygSzWtKzLzEMXy4kQcbnq75VhaAVSf'),
        asks: new PublicKey('EMgwBXyECv7nKjrifjwt5NdoJKZPS7TCvULPNB7XN9HY'),
        requestQueue: new PublicKey('QxVP3LFd1EEY212LBxL1fQpypGt7YPQh7X4vYk1XAKU'),
        eventQueue: new PublicKey('FGk1xV2qDpGgtuBSokUjCpb37e5fv8wDVaCvK2rQBmtp'),
        baseVault: new PublicKey('6kJkXA9ss3dJnRiz7nPk8UgpZgXETzzJFXHsHaN2JK8E'),
        quoteVault: new PublicKey('8EyEyZqDAhhh3BJTTApm6jkrTyWgvFf1r14yyB8XeLa3'),
        baseMint: new PublicKey('DHALxCahVckZxqt7SzjG3tSTnpydpJE2qsFk7axVDhMm'),
        quoteMint: new PublicKey('4B1DVNsjJbVRJyeFFfudQ8phHaXW2CdfG8RYdBiNdC3A'),
        vaultOwner: new PublicKey('CEUd6j3ZKH7feKtYJNj8JxN8T9rnLcryFpAmq81vJFQ'),
    },
    {
        name: 'BTC/USDC',
        address: new PublicKey('7ayQdHG4h9BQyUWGNmeU58UBPjQaVbkpVXPTFfx4pVdH'),
        leverage: 5,
        baseSymbol: 'BTC',
        quoteSymbol: 'USDC',
        marketIndex: 45,
        expiryIndex: 1,
        orderPriceDecimals: 4,
        orderQuantityDecimals: 3,
        greekNodeKey: new PublicKey('BTLpzbf3xbA9usJNBZ8ZpT4dJzgyG2TGnnXMZVH1ka4b'),
        zetaBaseVault: new PublicKey('3vQGr5ZuMeB6xXZkTDWggbCy94bdPtwSZVcYAM9i8noP'),
        zetaQuoteVault: new PublicKey('DFUswUXwZesLdvk2YaU7Z8YzinBUSyXiuoqJmfbQkCbi'),
        bids: new PublicKey('5HeLL4po1P55fmxKCAf67qyYuZPne2eKmwhib9QDSYzc'),
        asks: new PublicKey('4J1UEiwYNxL5fnbAGRcVERYesYV2a6XUKvQMVSxRBWZz'),
        requestQueue: new PublicKey('AyAZf5TynHrfBwYPbMkU9hX3bEHTQPokTox6WK1KmjWw'),
        eventQueue: new PublicKey('5nEDKv1NkNMPLqVpNKxYoudtuGXaQcsEXV9FxUXE9iyu'),
        baseVault: new PublicKey('ARTR2VWZcfSrH8GMF3JDBDm4TP3p2dBAvqVt7PKc1FFn'),
        quoteVault: new PublicKey('JC3Xn6TqkhRAQFKCW4grziLWKKZWmhit6om5zpS9x7Tj'),
        baseMint: new PublicKey('AhM1M85JmL77DeCcPVh7gCF9NP7bHuNphT9ez5g6aHyt'),
        quoteMint: new PublicKey('6fBnX78rRMNS7ZMsCTPfjvguiBNE5zLdioGzLvW4zkcK'),
        vaultOwner: new PublicKey('GUwD99aaZUCkMPk44M1eTKDjRcrBnco6jb9s7Y9x3ZsW'),
    },
    {
        name: 'ETH/USDC',
        address: new PublicKey('4A9WSdRr4ANz1izgiZx7yn17BqqJKz3R6NHNnqbCEUBK'),
        leverage: 5,
        baseSymbol: 'ETH',
        quoteSymbol: 'USDC',
        marketIndex: 22,
        expiryIndex: 0,
        orderPriceDecimals: 4,
        orderQuantityDecimals: 3,
        greekNodeKey: new PublicKey('798H5KUGcNXYsiZnE11iAtgYRQPPCqKWbhKZr3MP2NX2'),
        zetaBaseVault: new PublicKey('BWhCv8j63woXeJWSQZeTgfpNFvDGGZXPEzee2sf24XN4'),
        zetaQuoteVault: new PublicKey('44arqhvySh2FeWioHGYwk9xmG2HKcUfgsn5iCTVddFox'),
        bids: new PublicKey('5PjjLrxpL9A4msEq8wxCLafChTGDtGuB6guu7DdahMHx'),
        asks: new PublicKey('8JrvMgV17qAUKc92sx8F1dBr9uxPsuSFYVrTVAyFNcrX'),
        requestQueue: new PublicKey('2XE9UogQr5AWsFezrACgmtB4rGwvp2JXz6LVwiaxtWWJ'),
        eventQueue: new PublicKey('5iyZ77EtSuENywUaXECnyX2gvBNwSD8oXgFxrh36v3Bh'),
        baseVault: new PublicKey('QeuweZYLVXraveMNxYrs1AcKW2uPWmbRf2BPswRuZTZ'),
        quoteVault: new PublicKey('uEEx9N59XtZaMimxJtwb7VZUKLz3vPSD61QDKgnGwK6'),
        baseMint: new PublicKey('EhetHAcNHW3KaGdiQMouPn1zp5Y4kbNCnnYGeqJ9JiAR'),
        quoteMint: new PublicKey('4pdHFUcdBhw8pr4ygw52nhuKhJkbohj9Hxxuhq5qXpVZ'),
        vaultOwner: new PublicKey('J3XpoJiunwaP8p9KmkiU2UJyhaojFax9HLnPDhFduP2M'),
    },
    {
        name: 'ETH/USDC',
        address: new PublicKey('7kFe7bYSfGTVeBowWcVE2VRHtgTA5YTyMXLhddbrawza'),
        leverage: 5,
        baseSymbol: 'ETH',
        quoteSymbol: 'USDC',
        marketIndex: 45,
        expiryIndex: 1,
        orderPriceDecimals: 4,
        orderQuantityDecimals: 3,
        greekNodeKey: new PublicKey('ATvAsdK1PVDJXeRsUD3MvjfhqwUVAN1YjUxCWzScGpQC'),
        zetaBaseVault: new PublicKey('FN1VHiqcx3KUHFZtnq328y3gsw3FvYxtoqMS3MM1FXGW'),
        zetaQuoteVault: new PublicKey('4cUdYxuPANkVuh7EXsKLniRisNomn3BHFi6KXew1Mrxa'),
        bids: new PublicKey('J6gGFm11pSbnMNpUEgDnwAUit1uL8LN6MmhS8u4BDpM9'),
        asks: new PublicKey('QMissYZb3HWXU1tS3vqQQQH6LM7WBUUiHrX36FoFYdy'),
        requestQueue: new PublicKey('G1cRBNHTRH4gaYVirZMk4EtfRQU3t4iirhGNyXMBZpVb'),
        eventQueue: new PublicKey('H6a8Rt1ACXpP14FrBRJNmg8k9aTDmjfxb3e1edCYuSE1'),
        baseVault: new PublicKey('DXZEeBZdH8wkiivNABpwskGkazqYRPAbNPzmboVvDnhV'),
        quoteVault: new PublicKey('7SeRNGUw2ziFKgnUot5dCyJwQPgzfJLpyZ8BM8osLkVu'),
        baseMint: new PublicKey('8tgEAtnHFFcWKd5VhgE5nt3pbEAC4D1drEGcSA1ZGfBP'),
        quoteMint: new PublicKey('H9tywwzSFbqEuFPvYyvFfrQr7jaqAoRYx963Q2qGbFNA'),
        vaultOwner: new PublicKey('Hz15AZHpye8a3PE7u8K5Dqv9radzH9acWqbkYnX4Kh9H'),
    },
];

export const ZETA_PERP_MARKETS: ZetaPerpMarketConfig[] = [
    {
        name: 'SOL-PERP',
        address: new PublicKey('JE6d41JRokZAMUEAznV8JP4h7i6Ain6CyJrQuweRipFU'),
        leverage: 5,
        baseSymbol: 'SOL',
        quoteSymbol: 'USDC',
        orderPriceDecimals: 4,
        orderQuantityDecimals: 3,
        zetaBaseVault: new PublicKey('GYm6qTFwkGJx2ywetEuYrjHjhzVFCM2TwayyqS1HUPLG'),
        zetaQuoteVault: new PublicKey('7aXkF7AZE2D3h128eNJ7VVp72HCV1izjKFsJ8uNWtCFN'),
        bids: new PublicKey('HcjrQKnbqKJuxHDLNM9LJPyxcQs237waNZXW7RwgvAps'),
        asks: new PublicKey('Ec4xsLLgLc4wM5c19ZSvazE7M9Rtk2T6RzddNcSQKYGu'),
        requestQueue: new PublicKey('EaNR74nCjrYyNDsuoWmq19pH76QSd1nuTzvJSr3RDQ6x'),
        eventQueue: new PublicKey('3rjBffJkFa9zdGr9xmTVxF3y6nL6iL1pASVzym7s5FGr'),
        baseVault: new PublicKey('BEjGhNFnKT5weGtpBoFs5Y1mDN47Ntvag5aMV59nZRpk'),
        quoteVault: new PublicKey('CHBUBfU3zscTNsihdK3x44TbpTza1hwcsTUaZfk751b5'),
        baseMint: new PublicKey('2ZLdhFsrkAtdn9Kud4SZvqchQFvn5jVCHUdJ83vumKyR'),
        quoteMint: new PublicKey('BKt2FdgBahn77joeawhNidswFxfgasPYCHWghRL4AKBR'),
        vaultOwner: new PublicKey('3zqD2BwyXqKKjj5USunJTnFAij9g6ZaZVfVoRpr8XH2B'),
    },
    {
        name: 'BTC-PERP',
        address: new PublicKey('J5DTCqRAjX1FyzoP2A2HVmmaXuG971HJ8X1Z8Rvvd8uT'),
        leverage: 5,
        baseSymbol: 'BTC',
        quoteSymbol: 'USDC',
        orderPriceDecimals: 4,
        orderQuantityDecimals: 3,
        zetaBaseVault: new PublicKey('5mvaZWcZa4gB3JZptZuFAJnmDFfo1JovhqTkkfEcsryD'),
        zetaQuoteVault: new PublicKey('DboTtkWW3KPvT14fag8N6iDUyDXaT8FeBszGV9xdfBx2'),
        bids: new PublicKey('8JSbFw4YT3bzpbbHs1wKmRCSAmKucAba7XSUWj1p8xK5'),
        asks: new PublicKey('483SmqGQVxw3WDwcewMYHqC3Mu7ENxfTQJQtTR3ttpi7'),
        requestQueue: new PublicKey('6JSdqUr24mBt4MCQrZHRoSfeZbjgALx4MQunZwD8Uarg'),
        eventQueue: new PublicKey('4K1zxqAZn7bGAPN26W5mUaHrLMSpCk45gT4qVXwmfh39'),
        baseVault: new PublicKey('DbzL5mT4nBaxuAs8ti4UeT2qougRBdujxa7GhLndM5Jz'),
        quoteVault: new PublicKey('7M9xhY2ARnrkCaBK5SNM3Lyd3FdbTu2EWBwG4TQcqpsv'),
        baseMint: new PublicKey('63DZkAzoDXmzGzn9esoWSYpMLo4YB9oPHXreHKwuu4HA'),
        quoteMint: new PublicKey('DhMH8oRQoAAb6poHVsvCqq3NCMj6aKUH2tGQG5Lo4bCg'),
        vaultOwner: new PublicKey('ExV76Y8vas6rNibjnnKzC6xXxduyWvRHbF5gDrPUWXe8'),
    },
    {
        name: 'ETH-PERP',
        address: new PublicKey('J8x6y5G7GmTkuKTbbCAnfhn72vaUU2qsB6je9oKFigHM'),
        leverage: 5,
        baseSymbol: 'ETH',
        quoteSymbol: 'USDC',
        orderPriceDecimals: 4,
        orderQuantityDecimals: 3,
        zetaBaseVault: new PublicKey('8SH6uJe5rV13APZFQvkGdXPwTyeiLv67XTnv3EeYff3B'),
        zetaQuoteVault: new PublicKey('DhWWXYK2DSnCdK5rkAxJBkGb1SBR49RHpfHj2u1vobCJ'),
        bids: new PublicKey('CaqN8gomPEB1My2czRhetrj5ESKP3VRR3kwKhXtGxohG'),
        asks: new PublicKey('4oAjuVLt5N9au2X3bhYLSi9LRqtk4caBvSPQRwhXuEKP'),
        requestQueue: new PublicKey('A7D8zuxAmtui3XKz2VcxthAZ5HuwLbN74rrDapMJ3Z5d'),
        eventQueue: new PublicKey('CzK26LWpoU9UjSrZkVu97oZj63abJrNv1zp9Hy2zZdy5'),
        baseVault: new PublicKey('9YVE9r9cHFZNwm91p3Js8NBWVznesLSM8FZyswG2MG1B'),
        quoteVault: new PublicKey('DecjLCYjb7jdDp2UqA2MS4xjgDjZfvdgMjvkRW7oWs9L'),
        baseMint: new PublicKey('2Stzi7XE3btUQXaauTVB9brPAtPmGnrEDSJmp3w5VY2j'),
        quoteMint: new PublicKey('5Ehp2LtTRmjug39GphXhFEeguz7hGeg41N1U49wU8Kov'),
        vaultOwner: new PublicKey('53uJuK3KmRsVHhTVsrnJHGBxRQGZb5hEyW8NxwzyPaJC'),
    },
];
